### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mumbaigirl** [arjun-234/rasa-custom-connectors#1]
Do you mind reviewing your code , I tried this code , I code not get it to work. I think Instagram has changed it's APIs. Could you have a look .[Instagram API](https://developers.facebook.com/docs/messenger-platform/instagram/get-started/)

**Comment by arjun-234** [comment]
@thatcuteseller, please ensure you also verify this in the live mode of your meta app. Meta has implemented a new rule stating that messages and message_postback subscriptions in chatbots will only function in live mode.
